import { getCanonicalRedirectUrl } from "./src/lib/siteUrl";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore .open-next/worker.js is generated by the Cloudflare build.
import { default as handler } from "./.open-next/worker.js";

type WorkerEnv = {
  OFFICIAL_DOMAIN_NAME?: string;
};

type WorkerContext = {
  waitUntil(promise: Promise<unknown>): void;
  passThroughOnException(): void;
};

function createCanonicalRedirectResponse(redirectUrl: URL): Response {
  const response = Response.redirect(redirectUrl, 307);
  response.headers.set("Cache-Control", "no-store");
  return response;
}

const worker = {
  fetch(request: Request, env: WorkerEnv, ctx: WorkerContext): Response | Promise<Response> {
    const redirectUrl = getCanonicalRedirectUrl(new URL(request.url), env.OFFICIAL_DOMAIN_NAME);

    if (redirectUrl) {
      return createCanonicalRedirectResponse(redirectUrl);
    }

    return handler.fetch(request, env, ctx);
  },
};

export default worker;
