import { createWorker } from "./src/lib/workerRuntime";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore .open-next/worker.js is generated by the Cloudflare build.
import { default as handler } from "./.open-next/worker.js";

const worker = createWorker(handler);

export default worker;
